const HEADER_BAR_HEIGHT = 64;
const FIREBASE_COLLECTION_USERS = "users";
const MENU_ITEMS = {
  SETTINGS: "settings",
  LOGOUT: "logout"
};
export { HEADER_BAR_HEIGHT, FIREBASE_COLLECTION_USERS, MENU_ITEMS };
